# (generated with --quick)

import flask.cli
import jinja2.loaders
import threading
from typing import Any, Callable, Dict, IO, Iterable, List, Optional, Sequence, Tuple, Type, TypeVar, Union
import werkzeug.datastructures
import werkzeug.local
import werkzeug.wsgi

BadRequest: Any
BuildError: Any
FileSystemLoader: Type[jinja2.loaders.FileSystemLoader]
Headers: Type[werkzeug.datastructures.Headers]
NotFound: Any
RLock: Type[threading._RLock]
RequestedRangeNotSatisfiable: Any
_app_ctx_stack: werkzeug.local.LocalStack
_missing: Any
_os_alt_seps: List[Optional[str]]
_request_ctx_stack: werkzeug.local.LocalStack
current_app: werkzeug.local.LocalProxy
io: module
message_flashed: Any
mimetypes: module
os: module
pkgutil: module
posixpath: module
request: werkzeug.local.LocalProxy
session: werkzeug.local.LocalProxy
socket: module
sys: module
unicodedata: module

_T0 = TypeVar('_T0')

class _PackageBoundObject:
    _static_folder: None
    _static_url_path: None
    cli: flask.cli.AppGroup
    has_static_folder: bool
    import_name: Any
    jinja_loader: Any
    root_path: Any
    static_folder: Any
    static_url_path: Any
    template_folder: Any
    def __init__(self, import_name, template_folder = ..., root_path = ...) -> None: ...
    def get_send_file_max_age(self, filename) -> Any: ...
    def open_resource(self, resource, mode = ...) -> IO[Union[bytes, str]]: ...
    def send_static_file(self, filename) -> Any: ...

class locked_cached_property:
    __doc__: Any
    func: Any
    lock: threading._RLock
    def __get__(self, obj, type = ...) -> Any: ...
    def __init__(self, func, name = ..., doc = ...) -> None: ...

def _find_package_path(root_mod_name) -> Any: ...
def _matching_loader_thinks_module_is_package(loader, mod_name) -> Any: ...
def adler32(__data: bytes, __value: int = ...) -> int: ...
def find_package(import_name) -> Tuple[Any, Any]: ...
def flash(message, category = ...) -> None: ...
def get_debug_flag() -> Any: ...
def get_env() -> str: ...
def get_flashed_messages(with_categories = ..., category_filter = ...) -> Any: ...
def get_load_dotenv(default: _T0 = ...) -> Union[bool, _T0]: ...
def get_root_path(import_name) -> Any: ...
def get_template_attribute(template_name, attribute) -> Any: ...
def is_ip(value) -> bool: ...
def make_response(*args) -> Any: ...
def safe_join(directory, *pathnames) -> str: ...
def send_file(filename_or_fp, mimetype = ..., as_attachment = ..., attachment_filename = ..., add_etags = ..., cache_timeout = ..., conditional = ..., last_modified = ...) -> Any: ...
def send_from_directory(directory, filename, **options) -> Any: ...
def stream_with_context(generator_or_function) -> Any: ...
def time() -> float: ...
def total_seconds(td) -> Any: ...
def update_wrapper(wrapper: Callable, wrapped: Callable, assigned: Sequence[str] = ..., updated: Sequence[str] = ...) -> Callable: ...
def url_for(endpoint, **values) -> Any: ...
def url_quote(string, charset: str = ..., errors: str = ..., safe: str = ..., unsafe: str = ...) -> Any: ...
def wrap_file(environ: Dict[str, Any], file: werkzeug.wsgi._Readable, buffer_size: int = ...) -> Iterable[bytes]: ...
